"""Add payment_valid column to reservations

Revision ID: ac744cc8b7e4
Revises: 
Create Date: 2025-10-03 16:07:28.563990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac744cc8b7e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'county_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reservations', 'payment_valid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'payment_valid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('reservations', 'county_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
