"""allow user deletion without deleting reservations

Revision ID: 439c1f881ede
Revises: 34e01aef7eef
Create Date: 2025-10-28 14:58:27.877935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439c1f881ede'
down_revision: Union[str, None] = '34e01aef7eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'groom_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('reservations_groom_id_fkey', 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'users', ['groom_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key('reservations_groom_id_fkey', 'reservations', 'users', ['groom_id'], ['id'])
    op.alter_column('reservations', 'groom_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
