"""add_access_pages_password_to_users

Revision ID: e6e3bbd3e5ac
Revises: 12a356ef0cc9
Create Date: 2025-12-21 15:09:06.386703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6e3bbd3e5ac'
down_revision: Union[str, None] = '12a356ef0cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_pages_password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_pages_password_hash')
    # ### end Alembic commands ###
