"""add_years_max_reserv_columns_to_clan_settings

Revision ID: 78e2145de039
Revises: ac744cc8b7e4
Create Date: 2025-10-05 23:05:20.377684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78e2145de039'
down_revision: Union[str, None] = 'ac744cc8b7e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clan_settings', sa.Column(
        'years_max_reserv_GroomFromOutClan', sa.Integer(), nullable=True))
    op.add_column('clan_settings', sa.Column(
        'years_max_reserv_GrooomFromOriginClan', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clan_settings', 'years_max_reserv_GrooomFromOriginClan')
    op.drop_column('clan_settings', 'years_max_reserv_GroomFromOutClan')
    # ### end Alembic commands ###
