"""update the notification table 

Revision ID: 12a356ef0cc9
Revises: 9d7ecfe100b7
Create Date: 2025-11-20 11:22:27.128381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a356ef0cc9'
down_revision: Union[str, None] = '9d7ecfe100b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'reservation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'reservation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
