"""add new column on the special reservation table

Revision ID: 34e01aef7eef
Revises: 810631f31a88
Create Date: 2025-10-20 14:42:59.317387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34e01aef7eef'
down_revision: Union[str, None] = '810631f31a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations_special', sa.Column(
        'full_name', sa.String(), nullable=True))
    op.add_column('reservations_special', sa.Column(
        'home_address', sa.String(), nullable=True))
    op.add_column('reservations_special', sa.Column(
        'phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations_special', 'phone_number')
    op.drop_column('reservations_special', 'home_address')
    op.drop_column('reservations_special', 'full_name')
    # ### end Alembic commands ###
