"""Add ReservationSpecial model

Revision ID: 810631f31a88
Revises: 78e2145de039
Create Date: 2025-10-17 23:05:26.737048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '810631f31a88'
down_revision: Union[str, None] = '78e2145de039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations_special',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('clan_id', sa.Integer(), nullable=False),
                    sa.Column('county_id', sa.Integer(), nullable=False),
                    sa.Column('reserv_name', sa.String(), nullable=False),
                    sa.Column('reserv_desctiption',
                              sa.String(), nullable=True),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('status', sa.Enum('validated', 'cancelled',
                                                name='reservationspecialstatus'), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ),
                    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_reservations_special_id'),
                    'reservations_special', ['id'], unique=False)
    op.alter_column('clan_rules', 'rules_book_of_clan_pdf',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Text(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clan_rules', 'rules_book_of_clan_pdf',
                    existing_type=sa.Text(),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)
    op.drop_index(op.f('ix_reservations_special_id'),
                  table_name='reservations_special')
    op.drop_table('reservations_special')
    # ### end Alembic commands ###
