"""add new table caled notification also his routes nad shcemas files 

Revision ID: 5cf75cae97ae
Revises: 439c1f881ede
Create Date: 2025-11-17 14:35:48.205933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf75cae97ae'
down_revision: Union[str, None] = '439c1f881ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'groom_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('reservations_groom_id_fkey', 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'users', ['groom_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key('reservations_groom_id_fkey', 'reservations', 'users', ['groom_id'], ['id'])
    op.alter_column('reservations', 'groom_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
