"""Add payment_valid column to reservations

Revision ID: ac744cc8b7e4
Revises: 
Create Date: 2025-10-03 16:07:28.563990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac744cc8b7e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Change county_id to NOT NULL
    op.alter_column('reservations', 'county_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)

    # 2. Add payment_valid column (NEW COLUMN)
    # Check if column exists first to make migration idempotent
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('reservations')]

    if 'payment_valid' not in columns:
        op.add_column('reservations',
                      sa.Column('payment_valid', sa.Boolean(),
                                nullable=True, server_default='false')
                      )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'payment_valid')
    op.alter_column('reservations', 'county_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
