"""i have update the guardian_phone column so now is unique 

Revision ID: a48b7876d989
Revises: e7c88ea95e22
Create Date: 2026-01-23 21:05:02.468065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a48b7876d989'
down_revision: Union[str, None] = 'e7c88ea95e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'sms_to_groom_phone', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_guardian_phone'),
                    'users', ['guardian_phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_guardian_phone'), table_name='users')
    op.drop_column('users', 'sms_to_groom_phone')
    # ### end Alembic commands ###
