"""i have update the guardian_phone column so now is unique 

Revision ID: a48b7876d989
Revises: e7c88ea95e22
Create Date: 2026-01-23 21:05:02.468065

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a48b7876d989'
down_revision: Union[str, None] = 'e7c88ea95e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Add column as nullable with server default
    op.add_column('users', sa.Column(
        'sms_to_groom_phone', sa.Boolean(),
        server_default=sa.false(),
        nullable=True
    ))

    # Step 2: Update existing rows to have the default value
    op.execute(
        "UPDATE users SET sms_to_groom_phone = FALSE WHERE sms_to_groom_phone IS NULL")

    # Step 3: Make the column NOT NULL now that all rows have values
    op.alter_column('users', 'sms_to_groom_phone',
                    nullable=False,
                    server_default=sa.false())

    # Create unique index for guardian_phone
    op.create_index(op.f('ix_users_guardian_phone'),
                    'users', ['guardian_phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_guardian_phone'), table_name='users')
    op.drop_column('users', 'sms_to_groom_phone')
    # ### end Alembic commands ###
