""" updated reservation model 

Revision ID: e7c88ea95e22
Revises: 9db353fd874c
Create Date: 2026-01-21 10:56:01.571944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c88ea95e22'
down_revision: Union[str, None] = '9db353fd874c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('custom_madaeh_committee_name', sa.String(), nullable=True))
    op.add_column('reservations', sa.Column('tilawa_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'tilawa_type')
    op.drop_column('reservations', 'custom_madaeh_committee_name')
    # ### end Alembic commands ###
