"""i update the user model i add tow column of wakil info 

Revision ID: 534a420d4c69
Revises: 9b562a597077
Create Date: 2026-02-03 12:21:52.519899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534a420d4c69'
down_revision: Union[str, None] = '9b562a597077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wakil_full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('wakil_phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wakil_phone_number')
    op.drop_column('users', 'wakil_full_name')
    # ### end Alembic commands ###
